name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.5
      - name: Install dependencies
        run: |
          sudo apt-get install libre2-dev
          gem install bundler -v 2.2.5
          bundle install
      - name: Run
        run: bundle exec rake
